server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: "gestionCriptomonedas"
  devtools:
    add-properties: false
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/cryptocurrency_management"
    username: "postgres"
    password: "postgres"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
  jwt:
    jwtSecret: "HdTJ4HvAUze5yoIfxe6oc3I4vEW1tAXxMEJPXor/khw="
    jwtExpiration: "300000"
logging:
  level:
    org:
      hibernate:
        SQL: "debug"